name: Update README

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        env:
          GH_README_STATS_TOKEN: ${{ secrets.GH_README_STATS_TOKEN }}
        run: |
          curl -o stats.svg "https://github-readme-stats.vercel.app/api?username=tangent-tz&count_private=true&include_all_commits=true&theme=dracula&hide_border=false&show_icons=true&hide_title=false&hide_rank=false&disable_animations=false&locale=en&token=${GH_README_STATS_TOKEN}"
          curl -o langs.svg "https://github-readme-stats.vercel.app/api/top-langs?username=tangent-tz&count_private=true&theme=dracula&hide_border=false&locale=en&hide_title=false&layout=compact&card_width=320&langs_count=5&token=${GH_README_STATS_TOKEN}"
          # Replace placeholders in README.md
          sed -i 's|<!-- STATS_PLACEHOLDER -->|![](./stats.svg)|' README.md
          sed -i 's|<!-- LANGS_PLACEHOLDER -->|![](./langs.svg)|' README.md
      - name: Commit Changes
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git add .
          git commit -m 'Update README with latest stats' || exit 0
          git push
