name: Update README

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensures GITHUB_TOKEN is used
      - name: Generate GitHub Stats Images
        env:
          GH_README_STATS_TOKEN: ${{ secrets.GH_README_STATS_TOKEN }}
        run: |
          curl -H "Authorization: token ${GH_README_STATS_TOKEN}" \
            -o stats.svg \
            "https://github-readme-stats.vercel.app/api?username=tangent-tz&count_private=true&include_all_commits=true&theme=dracula&hide_border=false&show_icons=true&hide_title=false&hide_rank=false&disable_animations=false&locale=en"
          curl -H "Authorization: token ${GH_README_STATS_TOKEN}" \
            -o langs.svg \
            "https://github-readme-stats.vercel.app/api/top-langs?username=tangent-tz&count_private=true&theme=dracula&hide_border=false&locale=en&hide_title=false&layout=compact&card_width=320&langs_count=5"
      - name: Update README
        run: |
          sed -i '/<!-- STATS -->/!b;n;c\![Stats](./stats.svg)' README.md
          sed -i '/<!-- LANGS -->/!b;n;c\![Languages](./langs.svg)' README.md
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md stats.svg langs.svg
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git push
